version: '3.4'

services:
  mssql:
    restart: 'no'
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Amiens2020!
    volumes:
      - sqldata:/var/opt/mssql
    labels:
      - "net.maxime-baumann.iut"

  sqlcmd:
    restart: 'no'
    image: mcr.microsoft.com/mssql/server:2019-latest
    depends_on:
      - mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Amiens2020!
    command: >
      sh -c '/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Amiens2020!'
    labels:
      - "net.maxime-baumann.iut"

  redis:
    restart: 'no'
    image: redislabs/redisearch:2.2.6
    command: --loglevel verbose
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    labels:
      - "net.maxime-baumann.iut"

  rcli:
    restart: 'no'
    image: redislabs/redisearch:2.2.6
    depends_on:
      - redis
    command: >
      sh -c 'redis-cli -h redis '
    labels:
      - "net.maxime-baumann.iut"

  readis:
    restart: 'no'
    image: hollodotme/readis
    ports:
      - 8080:80
    volumes:
      - ./config:/code/config:ro
    depends_on:
      - redis
    labels:
      - "net.maxime-baumann.iut"

  phpredisadmin:
    restart: 'no'
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    ports:
      - 8081:80
    labels:
      - "net.maxime-baumann.iut"
      
  mongo:
    restart: 'no'
    image: mongo:4.4.11
    command: --serviceExecutor adaptive
    volumes:
      - mongodata:/data/db
    labels:
      - "net.maxime-baumann.iut"

  mgcli:
    restart: 'no'
    image: mongo:4.4.11
    depends_on:
      - mongo
    command: >
      sh -c 'mongo --host mongo '
    labels:
      - "net.maxime-baumann.iut"

  mongo-express:
    restart: 'no'
    image: mongo-express:0.54.0
    ports:
      - 8082:8081
    depends_on:
      - mongo
    labels:
      - "net.maxime-baumann.iut"

  neo4j:
    restart: 'no'
    image: neo4j:4.1.4
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neodata:/data
    labels:
      - "net.maxime-baumann.iut"

  pg:
    restart: 'no'
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Amiens2020!
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgcli:
    restart: 'no'
    image: postgres:14.1-alpine
    depends_on:
      - pg
    command: >
      sh -c 'psql -h pg -U postgres'

  adminer:
    restart: 'no'
    image: adminer:4.8.1-standalone
    ports:
      - 8083:8080

volumes:
  redisdata:
    labels:
      - "net.maxime-baumann.iut"
  sqldata:
    labels:
      - "net.maxime-baumann.iut"
  mongodata:
    labels:
      - "net.maxime-baumann.iut"
  neodata:
    labels:
      - "net.maxime-baumann.iut"
  pgdata:
    labels:
      - "net.maxime-baumann.iut"
